#!/bin/sh

xidlehook \
  --not-when-fullscreen \
  --not-when-audio \
  --timer 120 \
    'xrandr --output DVI-D-0 --brightness .5' \
    'xrandr --output DVI-D-0 --brightness 1' \
  --timer 20 \
    'xrandr --output DVI-D-0 --brightness 1; betterlockscreen -l' \
    ''\
  --timer 300 \
    'systemctl suspend' \
    ''
